version: '3.10'

services:

  bot:
    build:
      context: .
    container_name: wallfin
    restart: always
    depends_on:
      - db
      - redis
      - celery_worker
    env_file:
      - tg_bot/.env
    volumes:
      - .:/app

#скрыть данные бд

  db:
    image: postgres:14.6-alpine
    container_name: postgres_db
    restart: always
    env_file:
      - tg_bot/.env
    environment:
      POSTGRES_DB: wallfin
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: redis_cache
    restart: always
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - redis_data:/data

  celery_worker:
    build:
      context: .
    container_name: celery_worker
    restart: always
    depends_on:
      - redis
      - db
    env_file:
      - tg_bot/.env
    command: celery -A celery_app worker --loglevel=info
    volumes:
      - .:/app

  celery_beat:
    build:
      context: .
    container_name: celery_beat
    restart: always
    depends_on:
      - redis
      - db
      - celery_worker
    env_file:
      - tg_bot/.env
    command: celery -A celery_app beat --loglevel=info
    volumes:
      - .:/app

volumes:
  postgres_data:
  redis_data: